const USER_DATA = {
    LOAD_DATA_LOADING: 'LOAD_DATA_LOADING',
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_DATA_ERROR: 'LOAD_DATA_ERROR',
};

const CDM_WORDS = {
    LOAD_CDM_WORDS_LOADING: 'LOAD_CDM_WORDS_LOADING',
    LOAD_CDM_WORDS_SUCCESS: 'LOAD_CDM_WORDS_SUCCESS',
    LOAD_CDM_WORDS_ERROR: 'LOAD_CDM_WORDS_ERROR',
};

export { USER_DATA, CDM_WORDS };
