const USER_DATA = {
    LOAD_USER_DATA_LOADING: 'LOAD_USER_DATA_LOADING',
    LOAD_USER_DATA_SUCCESS: 'LOAD_USER_DATA_SUCCESS',
    LOAD_USER_DATA_ERROR: 'LOAD_USER_DATA_ERROR',
};

const CDM_WORDS = {
    LOAD_CDM_WORDS_LOADING: 'LOAD_CDM_WORDS_LOADING',
    LOAD_CDM_WORDS_SUCCESS: 'LOAD_CDM_WORDS_SUCCESS',
    LOAD_CDM_WORDS_ERROR: 'LOAD_CDM_WORDS_ERROR',
};

const KEYWORDS_MAPTO_CDM_WORDS = {
    SET_KEYWORDS_MAPTO_CDM_WORDS: 'SET_KEYWORDS_MAPTO_CDM_WORDS',
};

export { USER_DATA, CDM_WORDS, KEYWORDS_MAPTO_CDM_WORDS };
